language: go

go:
  - tip

# TODO
# linux/386 build tries to do apt's legendary remove all 64-bit libraries and install 32-bit ones instead (else it can't find sys/types.h) so that build is disabled for now

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -y libgtk-3-dev multiarch-support # libgtk-3-0:i386 gcc-multilib
 - go tool dist install cmd/8a
 - go tool dist install cmd/8c
 - go tool dist install cmd/8g
 - go tool dist install cmd/8l
# - GOOS=linux GOARCH=386 CGO_ENABLED=1 CFLAGS=-m32 LDFLAGS=-m32 go tool dist install pkg/runtime
# - GOOS=linux GOARCH=386 CGO_ENABLED=1 CFLAGS=-m32 LDFLAGS=-m32 go install std
 - GOOS=windows GOARCH=386 go tool dist install pkg/runtime
 - GOOS=windows GOARCH=386 go install std
 - GOOS=windows GOARCH=amd64 go tool dist install pkg/runtime
 - GOOS=windows GOARCH=amd64 go install std

install:
 - GOOS=linux GOARCH=amd64 ./test.sh -v -x
 - GOOS=windows GOARCH=386 ./test.sh -v -x
 - GOOS=windows GOARCH=amd64 ./test.sh -v -x
